// vue-tour-of-heroes/src/components/Messages.vue
<template>
  <div v-if="messageService.messages.length">
    <h2>Messages</h2>
    <button class="clear" @click="messageService.clear()">
      Clear messages
    </button>
    <div v-for="(message, index) of messageService.messages" :key="index">
      {{ message }}
    </div>
  </div>
</template>

<script lang="ts">
import { MessageService } from "@/store/message-service";
import { keys } from "@/keys";
import { defineComponent, inject } from "vue";

export default defineComponent({
  setup() {
    const messageService = inject(keys.messageServiceKey) as MessageService;

    return {
      messageService,
    };
  },
});
</script>

<style lang="scss" scoped>
/* MessagesComponent's private CSS styles */
h2 {
  color: #a80000;
  font-family: Arial, Helvetica, sans-serif;
  font-weight: lighter;
}

.clear {
  color: #333;
  background-color: #eee;
  margin-bottom: 12px;
  padding: 1rem;
  border-radius: 4px;
  font-size: 1rem;
}
.clear:hover {
  color: white;
  background-color: #42545c;
}
</style>

// nextjs-tour-of-heroes/components/messages/messages.tsx
import { FunctionComponent } from 'react';

import { useAppDispatch } from '@hooks';
import { MessageServiceActions as MSA, useMessageService } from '@store/message-service';

import styles from './Messages.module.scss';

const Messages: FunctionComponent = () => {
  const messageService = useMessageService();
  const dispatch = useAppDispatch();

  return (<>
    { messageService.messages.length !== 0 &&
      <div>

        <h2 className={styles.h2}>Messages</h2>
        <button
          className={styles.clear}
          onClick={() => dispatch(MSA.clear())}
        >
          Clear messages
        </button>
        { messageService.messages.map((message: string, index: number) => (
          <div key={index}>
            {message}
          </div>
        ))}
      </div>
    }
  </>);
};

export default Messages
