// nextjs-tour-of-heroes/components/hero-detail/hero-detail.tsx
import { useRouter } from 'next/router';
import { FunctionComponent, useCallback, useEffect, useState } from 'react';
import { tap } from 'rxjs';

import { useHeroService } from '@hooks/hero-service';
import { Hero } from '@models/hero';
import { uppercase } from '@utils/uppercase';

import styles from './Hero-detail.module.scss';

interface Props {
  hero?: Hero;
  handleChange?: (value: string) => void;
}

const HeroDetail: FunctionComponent = () => {
  const [hero, setHero] = useState<Hero>();
  const heroService = useHeroService();
  const router = useRouter();
  const { id } = router.query;

  const getHero = useCallback((): void => {
    heroService.getHero(Number(id)).pipe(
      tap(setHero),
    ).subscribe();
  }, [heroService, id]);

  const goBack = (): void => {
    router.back();
  }

  const save = (): void => {
    if (hero) {
      heroService.updateHero(hero).pipe(
        tap(goBack),
      ).subscribe();
    }
  }

  const handleChange = (name: string): void => {
    setHero({...hero!, name});
  }

  useEffect(() => {
    getHero();
  }, [getHero])

  return (<>
    { hero &&
      <div>

        <h2>{uppercase(hero.name)} Details</h2>
        <div><span>id: </span>{hero.id}</div>
        <div>
          <label className={styles.label} htmlFor="name">Hero name: </label>
          <input
            id="name"
            className={styles.input}
            value={hero.name}
            onChange={(event) => handleChange(event.target.value)}
            placeholder="Hero name"
          />
        </div>

        <button className={styles.button} onClick={goBack}>go back</button>
        <button className={styles.button} onClick={save}>save</button>
      </div>
    }
  </>);
}

export default HeroDetail

// angular-tour-of-heroes/src/app/hero-detail/hero-detail.component.ts
import { tap } from 'rxjs';
import { Hero } from 'src/app/hero';

import { Location } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

import { HeroService } from '../hero.service';

@Component({
  selector: 'app-hero-detail',
  templateUrl: 'hero-detail.component.html',
  styleUrls: ['hero-detail.component.scss']
})
export class HeroDetailComponent implements OnInit {
  hero: Hero | undefined;

  constructor(
    private route: ActivatedRoute,
    private heroService: HeroService,
    private location: Location,
  ) {}

  ngOnInit(): void {
    this.getHero();
  }

  getHero(): void {
    const id = Number(this.route.snapshot.paramMap.get('id'));
    this.heroService.getHero(id).pipe(
      tap(hero => this.hero = hero)
    ).subscribe();
  }

  goBack(): void {
    this.location.back();
  }

  save(): void {
    if (this.hero) {
      this.heroService.updateHero(this.hero).pipe(
        tap(() => this.goBack()),
      ).subscribe();
    }
  }
}

<div *ngIf="hero">

  <h2>{{hero.name | uppercase}} Details</h2>
  <div><span>id: </span>{{hero.id}}</div>
  <div>
    <label for="hero-name">Hero name: </label>
    <input id="hero-name" [(ngModel)]="hero.name" placeholder="Hero name">
  </div>

  <button (click)="goBack()">go back</button>
  <button (click)="save()">save</button>
</div>
