// nextjs-tour-of-heroes/components/heroes/heroes.tsx
import { FunctionComponent, useState } from 'react';

import { Hero } from '../../models/hero';
import { uppercase } from '../../utils/uppercase';
import styles from './Heroes.module.scss';

const Heroes: FunctionComponent = () => {
  const [hero, setHero] = useState<Hero>({
    id: 1,
    name: 'Windstorm',
  });

  return (<>
    <h2>{uppercase(hero.name)} Details</h2>
    <div><span>id: </span>{hero.id}</div>
    <div>
      <label htmlFor="name">Hero name: </label>
      <input
        id="name"
        value={hero.name}
        onChange={(event) => setHero({...hero, name: event.target.value})}
        placeholder="name"
      />
    </div>
  </>);
}

export default Heroes

// vue-tour-of-heroes/src/components/Heroes.vue
<template>
  <div>
    <h2>{{$filters.uppercase(hero.name)}} Details</h2>
    <div><span>id: </span>{{hero.id}}</div>
    <div>
      <label for="name">Hero name: </label>
      <input id="name" v-model="hero.name" placeholder="name">
    </div>
  </div>
</template>

<script lang="ts">
import { Options, Vue } from 'vue-class-component';

import { Hero } from '../models/hero';

@Options({})
export default class Heroes extends Vue {
  hero: Hero = {
    id: 1,
    name: 'Windstorm',
  };
}
</script>

<style lang="scss" scoped>

</style>
