// nextjs-tour-of-heroes/components/hero-search/hero-search.tsx
import classNames from 'classnames';
import Link from 'next/link';
import { FunctionComponent, useCallback, useEffect, useState } from 'react';
import { debounceTime, distinctUntilChanged, Subject, switchMap, tap } from 'rxjs';

import { useHeroService } from '@hooks/hero-service';
import { Hero } from '@models/hero';

import styles from './Hero-search.module.scss';

const HeroSearch: FunctionComponent = () => {
  const [heroes, setHeroes] = useState<Hero[]>([]);
  const heroService = useHeroService();
  const searchTerms = useState(new Subject<string>())[0];

  const search = useCallback((term: string): void => {
    searchTerms.next(term);
  }, [searchTerms]);

  useEffect(() => {
    const subscription = searchTerms.pipe(
      debounceTime(300),
      distinctUntilChanged(),
      switchMap((term: string) => heroService.searchHeroes(term)),
      tap(setHeroes),
    ).subscribe();

    return () => {
      subscription.unsubscribe();
    }
  }, [heroService, searchTerms]);

  return (<>
    <div id="search-component">
      <label className={styles.label} htmlFor="search-box">Hero Search</label>
      <input
        className={styles.input}
        id="search-box"
        onChange={(event) => search(event.target.value)}
      />

      <ul className={classNames(styles['search-result'], styles.ul)}>
        { heroes.map(hero =>
          <li className={styles.li} key={hero.id}>
            <Link href={`/detail/${hero.id}`}>
              <a>
                {hero.name}
              </a>
            </Link>
          </li>
        )}
      </ul>
    </div>
  </>)
}

export default HeroSearch

// angular-tour-of-heroes/src/app/hero-search/hero-search.component.ts
import { debounceTime, distinctUntilChanged, Observable, Subject, switchMap } from 'rxjs';
import { Hero } from 'src/app/hero';
import { HeroService } from 'src/app/hero.service';

import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-hero-search',
  templateUrl: 'hero-search.component.html',
  styleUrls: ['hero-search.component.scss']
})
export class HeroSearchComponent implements OnInit {
  heroes$!: Observable<Hero[]>;
  private searchTerms = new Subject<string>();

  constructor(private heroService: HeroService) {}

  search(term: string): void {
    this.searchTerms.next(term);
  }

  ngOnInit(): void {
    this.heroes$ = this.searchTerms.pipe(
      debounceTime(300),
      distinctUntilChanged(),
      switchMap((term: string) => this.heroService.searchHeroes(term)),
    );
  }
}
