// angular-tour-of-heroes/src/app/dashboard/dashboard.component.ts
import { tap } from 'rxjs';

import { Component, OnInit } from '@angular/core';

import { Hero } from '../hero';
import { HeroService } from '../hero.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: [ './dashboard.component.scss' ]
})
export class DashboardComponent implements OnInit {
  heroes: Hero[] = [];

  constructor(private heroService: HeroService) { }

  ngOnInit(): void {
    this.getHeroes();
  }

  getHeroes(): void {
    this.heroService.getHeroes().pipe(tap(
      heroes => this.heroes = heroes.slice(1, 5)
    )).subscribe();
  }
}

<h2>Top Heroes</h2>
<div class="heroes-menu">
  <a
    *ngFor="let hero of heroes"
    routerLink="/detail/{{hero.id}}"
  >
    {{hero.name}}
  </a>
</div>

// nextjs-tour-of-heroes/components/dashboard/dashboard.tsx
import Link from 'next/link';
import { FunctionComponent, useCallback, useEffect, useState } from 'react';
import { map, tap } from 'rxjs';

import { useHeroService } from '@hooks/hero-service';
import { Hero } from '@models/hero';

import styles from './Dashboard.module.scss';

const Dashboard: FunctionComponent = () => {
  const [heroes, setHeroes] = useState<Hero[]>([]);
  const heroService = useHeroService();

  const getHeroes = useCallback((): void => {
    heroService.getHeroes().pipe(
      map(heroes => heroes.slice(1, 5)),
      tap(setHeroes),
    ).subscribe();
  }, [heroService]);

  useEffect(() => {
    getHeroes()
  }, [getHeroes]);

  return (<>
    <h2 className={styles.h2}>Top Heroes</h2>
    <div className={styles['heroes-menu']}>
      {heroes.map(hero =>
        <Link href={`/detail/${hero.id}`} key={hero.id}>
          <a className={styles.a}>
            {hero.name}
          </a>
        </Link>
      )}
    </div>
  </>)
}

export default Dashboard
