// vue-tour-of-heroes/src/components/Hero-detail.vue
<template>
  <div v-if="hero">
    <h2>{{ heroName }} Details</h2>
    <div><span>id: </span>{{ hero.id }}</div>
    <div>
      <label for="hero-name">Hero name: </label>
      <input id="hero-name" v-model="hero.name" placeholder="Hero name" />
    </div>
    <button @click="goBack()">go back</button>
    <button @click="save()">save</button>
  </div>
</template>

<script lang="ts">
import { computed, defineComponent, inject, ref } from "vue";

import { Hero } from "@/models/hero";
import { uppercase } from "@/utils/uppercase";
import { useRoute, useRouter } from "vue-router";
import { HeroService, heroServiceKey } from "@/services/hero-service";
import { tap } from "rxjs";

export default defineComponent({
  setup() {
    const hero = ref<Hero>();
    const heroName = computed(() => uppercase(hero.value?.name));
    const heroService = inject(heroServiceKey) as HeroService;
    const route = useRoute();
    const router = useRouter();

    const getHero = (): void => {
      const id = Number(route.params.id);
      heroService
        .getHero(id)
        .pipe(tap((HERO) => (hero.value = HERO)))
        .subscribe();
    };

    const goBack = (): void => {
      router.back();
    };

    const save = (): void => {
      if (hero.value) {
        heroService
          .updateHero(hero.value)
          .pipe(tap(() => goBack()))
          .subscribe();
      }
    };

    getHero();

    return {
      hero,
      heroName,
      getHero,
      goBack,
      save,
    };
  },
});
</script>

<style lang="scss" scoped>
/* HeroDetailComponent's private CSS styles */
label {
  color: #435960;
  font-weight: bold;
}
input {
  font-size: 1em;
  padding: 0.5rem;
}
button {
  margin-top: 20px;
  background-color: #eee;
  padding: 1rem;
  border-radius: 4px;
  font-size: 1rem;
}
button:hover {
  background-color: #cfd8dc;
}
button:disabled {
  background-color: #eee;
  color: #ccc;
  cursor: auto;
}
</style>

// nextjs-tour-of-heroes/components/hero-detail/hero-detail.tsx
import { useRouter } from 'next/router';
import { FunctionComponent, useCallback, useEffect, useState } from 'react';
import { tap } from 'rxjs';

import { useHeroService } from '@hooks/hero-service';
import { Hero } from '@models/hero';
import { uppercase } from '@utils/uppercase';

import styles from './Hero-detail.module.scss';

interface Props {
  hero?: Hero;
  handleChange?: (value: string) => void;
}

const HeroDetail: FunctionComponent = () => {
  const [hero, setHero] = useState<Hero>();
  const heroService = useHeroService();
  const router = useRouter();
  const { id } = router.query;

  const getHero = useCallback((): void => {
    heroService.getHero(Number(id)).pipe(
      tap(setHero),
    ).subscribe();
  }, [heroService, id]);

  const goBack = (): void => {
    router.back();
  }

  const save = (): void => {
    if (hero) {
      heroService.updateHero(hero).pipe(
        tap(goBack),
      ).subscribe();
    }
  }

  const handleChange = (name: string): void => {
    setHero({...hero!, name});
  }

  useEffect(() => {
    getHero();
  }, [getHero])

  return (<>
    { hero &&
      <div>

        <h2>{uppercase(hero.name)} Details</h2>
        <div><span>id: </span>{hero.id}</div>
        <div>
          <label className={styles.label} htmlFor="name">Hero name: </label>
          <input
            id="name"
            className={styles.input}
            value={hero.name}
            onChange={(event) => handleChange(event.target.value)}
            placeholder="Hero name"
          />
        </div>

        <button className={styles.button} onClick={goBack}>go back</button>
        <button className={styles.button} onClick={save}>save</button>
      </div>
    }
  </>);
}

export default HeroDetail
